import React from "react";
import styled from "styled-components";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
// import { Link } from "react-router-dom";
import jbplogo from "../../photos/jbplogo.png";

const responsive = {
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 1,
    slidesToSlide: 1, // optional, default to 1.
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 1,
    slidesToSlide: 1, // optional, default to 1.
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
    slidesToSlide: 1, // optional, default to 1.
  },
};

const StoryPart = () => {
  return (
    <>
      <Container>
        {/* <h1 className="text-center mt-5 mb-5">Media</h1> */}
        <Carousel
          // swipeable={true}
          // draggable={true}
          // showDots={true}
          responsive={responsive}
          // ssr={true} // means to render carousel on server-side.
          // infinite={true}
          // autoPlay={true}
          autoPlaySpeed={1000}
          keyBoardControl={true}
          // customTransition="all 5s ease-in-out"
          transitionDuration={1000}
          containerClass="carousel-container"
          removeArrowOnDeviceType={["tablet", "mobile"]}
          // deviceType={this.props.deviceType}
          dotListClass="custom-dot-list-style"
          itemClass="carousel-item-padding-40-px"
        >
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mg-card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="my-slide-component container">
              <div class="card mt-5">
                <div class="card-body">
                  <img src={jbplogo} alt="Card" className="card-image" />
                  <div className="cardp mt-5 text-start">
                    <p className="fw-bold">UHID : 123</p>
                    <p> Patient Name : Name Of The Patient</p>
                    <p>Assigned Doctor : Name of Assigned Doctor</p>
                    <p>Department : Name of the Department</p>
                    <p>Token Generated by : Name of Receptionist</p>
                    <p>Token generated on Date: Current Date & Time</p>
                    <p>Room No : Room No of Assigned Doctor</p>
                    <p>Counter No : Number Of Counter</p>
                  </div>

                  <div className="card-content mt-5">
                    <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Carousel>
        ;
      </Container>
    </>
  );
};

export default StoryPart;
const Container = styled.div`
.my-slide-component{
  display:flex;
  justify-content:center;
  align-items:center;

}
// .mg-card{
//   border: 2px solid black !important;
// }
  .card {
    border: 1px solid black !important;
  }
  .my-slide-component container{
    width: 100%,
    height: 100%,
  }

  span {
    @media (max-width: 500px) {
      display: none;
    }
    @media (max-width: 376px) {
      display: none;
    }
  }
  img {
    @media (max-width: 500px) {
      width: 18rem;
    }
    @media (max-width: 376px) {
      width: 18rem;
    }
  }
  .card-body{
    display: flex,
    flex-direction: column,
    justify-content: center,
    align-content: center,
    align-items: center,
  }
  p{
    margin:0;
  }
`;
