import React from "react";
import pic from "../photos/jbplogo.png";

import "./DoctorTreatment.css";

function DoctorTreatment() {
  return (
    <>
      <div className="header">
        <img className="img1" alt="img" src={pic} />
        <h1 className="adm1">Doctor`s Treatment</h1>
        <h3 className="hd">
          Hi, Admin Name <br />
          Employee Id
        </h3>
        <button className="btn1">Logout</button>
      </div>
      <div className="container">
        <button className="pre-btn" onClick>
          <p>&lt;</p>
        </button>
        <button className="next-btn" onClick>
          <p>&gt;</p>
        </button>

        <div className="card">
          <div className="carddesign">
            <div>
              <img className="img2" alt="img" src={pic} />

              <h1>PID :123</h1>
              <h3>Patient Name : Name of The Patient</h3>
              <h3>Assigned Doctor : Name of Assigned Doctor</h3>
              <h3>Department : Name of Department </h3>
              <h3>Token Generated By : Name of Receptionist</h3>
              <h3>Room No : Room No of Assigned Doctor</h3>
              <h3>Count No : Number Of Counter</h3>

              <br />
              <h1>Token No : DEPID_DATE_09</h1>
            </div>
          </div>

          <br />
          <div className="carddesign">
            <div>
              <img className="img2" alt="img" src={pic} />

              <h1>PID :123</h1>
              <h3>Patient Name : Name of The Patient</h3>
              <h3>Assigned Doctor : Name of Assigned Doctor</h3>
              <h3>Department : Name of Department </h3>
              <h3>Token Generated By : Name of Receptionist</h3>
              <h3>Room No : Room No of Assigned Doctor</h3>
              <h3>Count No : Number Of Counter</h3>

              <br />
              <h1>Token No : DEPID_DATE_09</h1>
            </div>
          </div>

          <div className="carddesign">
            <div>
              <img className="img2" alt="img" src={pic} />

              <h1>PID :123</h1>
              <h3>Patient Name : Name of The Patient</h3>
              <h3>Assigned Doctor : Name of Assigned Doctor</h3>
              <h3>Department : Name of Department </h3>
              <h3>Token Generated By : Name of Receptionist</h3>
              <h3>Room No : Room No of Assigned Doctor</h3>
              <h3>Count No : Number Of Counter</h3>

              <br />
              <h1>Token No : DEPID_DATE_09</h1>
            </div>
          </div>

          <div className="carddesign">
            <div>
              <img className="img2" alt="img" src={pic} />

              <h1>PID :123</h1>
              <h3>Patient Name : Name of The Patient</h3>
              <h3>Assigned Doctor : Name of Assigned Doctor</h3>
              <h3>Department : Name of Department </h3>
              <h3>Token Generated By : Name of Receptionist</h3>
              <h3>Room No : Room No of Assigned Doctor</h3>
              <h3>Count No : Number Of Counter</h3>

              <br />
              <h1>Token No : DEPID_DATE_09</h1>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default DoctorTreatment;
