import React, { useEffect, useState } from "react";
import Header from "./Header";
import jbplogo from "../photos/jbplogo.png";
import styled from "styled-components";
import { Link } from "react-router-dom";
import axios from "axios";

const Tokengenerated = () => {
  const [patient, setPatient] = useState([]);
  const domain = process.env.REACT_APP_DOMAIN;
  const getAllPatients = async () => {
    try {
      const response = await axios.get(
        `https://api.dvjei.org/api/auth/tokenReciept`
      );
      const data = response.data;
      const lastToken = data[data.length - 1];
      setPatient(lastToken);
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  useEffect(() => {
    getAllPatients();
  }, []);

  console.log(patient);
  return (
    <>
      <Container>
        <Header />
        <div className="container genToken">
          <h1 className="text-center fs-1 fw-bold" style={{ color: "#347571" }}>
            Token Generated
          </h1>

          <div class="card mt-5">
            <div class="card-body">
              <img src={jbplogo} alt="Card" className="card-image" />
              <div className="cardp mt-5 text-start">
                <p className="fw-bold">UHID : {patient.uhid}</p>
                <p>
                  {" "}
                  Patient Name : {patient.firstname} {patient.lastname}
                </p>
                <p>Assigned Doctor : {patient.Doctor_name}</p>
                <p>Department : {patient.Dept}</p>
                <p>Token Generated by : {patient.fullname}</p>
                <p>Token generated on Date: {patient.regdatetime}</p>
                <p>Room No : {patient.Room_No}</p>
                <p>Counter No :{patient.Counter_No}</p>
              </div>

              <div className="card-content mt-5">
                <h2 className="cardh"> Token No: {patient.Token_ID}</h2>
              </div>
            </div>
          </div>
          <div className="container foot-btn">
            <div className="row g-3">
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>Send Token as SMS</button>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>Print Token</button>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>
                  <Link to="/receptionist-dashboard">Go To Dashboard</Link>
                </button>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>
                  {" "}
                  <Link to="/token-gen-form">
                    Generate Token for other Patient
                  </Link>
                </button>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </>
  );
};
export default Tokengenerated;
const Container = styled.div`
  .genToken {
    height: 100%;
    display: flex;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    align-items: center;
  }
  .image {
    width: 35rem;
  }
  .card {
    width: 35rem;
    border: 2px solid black;
    .card-content {
    }
  }
  .card-body {
    display: flex;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    align-items: center;
    .cardp {
    }
  }
  .cardp {
    margin-left: -4rem;
    p {
      margin: 0;
    }
  }

  .foot-btn {
    width: 60%;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .btnText {
    display: flex;
    justify-content: center;
  }

  button {
    padding: 0.7rem 1.5rem;
    border: none;
    color: #fff;
    font-weight: bold;
    background-color: #5ec57e;
    border-radius: 1.5rem;
  }
  a {
    text-decoration: none;
    color: white;
  }
`;
