import axios from "axios";
// import pic from "../photos/jbplogo.png";
import "./AddRecptionist.css";
import Header from "./Header";
import { styled } from "styled-components";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import cogoToast from "cogo-toast";

const TokenGenForm = () => {
  const navigate = useNavigate();
  const [data, setData] = useState({
    Token_ID: "",
    uhid: "",
    P_Email: "",
    P_Contact: "",
    Assigned_doctor: "",
    Time: "",
    Dept: "",
    Token_Generated: "",
    Token_Generated_by: "",
    Room_No: "",
    Counter_No: "",
  });

  const domain = process.env.REACT_APP_DOMAIN;
  const handleChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
    console.log(data);
  };

  const handleClick = async (e) => {
    e.preventDefault();

    try {
      const input = await axios.post(
        `https://queuemanagementsystemdg.com/api/auth/PatientTokenGeneration`,
        data
      );

      console.log(input);
      cogoToast.success("Token generated successful");
      navigate("/token-generated");
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <Container>
        <Header />
        <h1 className="text-center fs-1 fw-bold" style={{ color: "#347571" }}>
          Generate Token
        </h1>
        <form onSubmit={handleClick}>
          <div className="form">
            <input
              type="text"
              placeholder="Token ID"
              style={{ border: "none" }}
              name="Token_ID"
              value={data.Token_ID}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Patient ID"
              style={{ border: "none" }}
              name="uhid"
              value={data.uhid}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Email"
              style={{ border: "none" }}
              name="P_Email"
              value={data.P_Email}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Patient Contact"
              style={{ border: "none" }}
              value={data.P_Contact}
              name="P_Contact"
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Assigned Doctor's Email"
              style={{ border: "none" }}
              value={data.Assigned_doctor}
              onChange={handleChange}
              name="Assigned_doctor"
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Time"
              style={{ border: "none" }}
              name="Time"
              value={data.Time}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Dept"
              style={{ border: "none" }}
              value={data.Dept}
              name="Dept"
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Token Generated"
              style={{ border: "none" }}
              name="Token_Generated"
              value={data.Token_Generated}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Token Generated by"
              style={{ border: "none" }}
              name="Token_Generated_by"
              value={data.Token_Generated_by}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Room Number"
              style={{ border: "none" }}
              name="Room_No"
              value={data.Room_No}
              onChange={handleChange}
              required
            />
            <br />
            <br />
            <input
              type="text"
              placeholder="Token Generated by"
              style={{ border: "none" }}
              name="Counter_No"
              value={data.Counter_No}
              onChange={handleChange}
              required
            />
            <br />
          </div>
          <div className="d-flex justify-content-center">
            <button type="submit" className="btn">
              Submit
            </button>
          </div>
        </form>
      </Container>
    </>
  );
};

export default TokenGenForm;
const Container = styled.div`
  input {
    padding: 0.5rem;
  }
`;
