import React from "react";
import "./Tokengenerated.css";
import Header from "./Header";
import jbplogo from "../photos/jbplogo.png";
import styled from "styled-components";
import { Link } from "react-router-dom";

const Tokengenerated = () => {
  return (
    <>
      <Container>
        <Header />
        <div className="container genToken">
          <h1 className="text-center fs-1 fw-bold" style={{ color: "#347571" }}>
            Token Generated
          </h1>

          <div class="card mt-5">
            <div class="card-body">
              <img src={jbplogo} alt="Card" className="card-image" />
              <div className="cardp mt-5 text-start">
                <p className="fw-bold">UHID : 123</p>
                <p> Patient Name : Name Of The Patient</p>
                <p>Assigned Doctor : Name of Assigned Doctor</p>
                <p>Department : Name of the Department</p>
                <p>Token Generated by : Name of Receptionist</p>
                <p>Token generated on Date: Current Date & Time</p>
                <p>Room No : Room No of Assigned Doctor</p>
                <p>Counter No : Number Of Counter</p>
              </div>

              <div className="card-content mt-5">
                <h2 className="cardh"> Token No: DEPID_DATE_01</h2>
              </div>
            </div>
          </div>
          <div className="container foot-btn">
            <div className="row g-3">
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>Send Token as SMS</button>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>Print Token</button>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>Go To Dashboard</button>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 btnText">
                <button>Generate Token for other Patient</button>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </>
  );
};
export default Tokengenerated;
const Container = styled.div`
  .genToken {
    height: 100%;
    display: flex;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    align-items: center;
  }
  .image {
    width: 35rem;
  }
  .card {
    width: 35rem;
    border: 2px solid black;
    .card-content {
    }
  }
  .card-body {
    display: flex;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    align-items: center;
    .cardp {
    }
  }
  .cardp {
    margin-left: -4rem;
    p {
      margin: 0;
    }
  }

  .foot-btn {
    width: 60%;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .btnText {
    display: flex;
    justify-content: center;
  }

  button {
    padding: 0.7rem 1.5rem;
    border: none;
    color: #fff;
    font-weight: bold;
    background-color: #5ec57e;
    border-radius: 1.5rem;
  }
`;
